// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkwohhhhyumamutqolqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrd29oaGhoeXVtYW11dHFvbHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjI1MjMsImV4cCI6MjA1Nzg5ODUyM30.biR8ZDMSuX9ICH1F71CNPauiyN6UZO--SFSWUdSfd-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);